
------------ Eliminación de tablas    ------------------

IF OBJECT_ID('LOREM_IPSUM.BI_H_VENTAS','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_H_VENTAS;

IF OBJECT_ID('LOREM_IPSUM.BI_H_PAGOS','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_H_PAGOS;

IF OBJECT_ID('LOREM_IPSUM.BI_H_ENVIOS','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_H_ENVIOS;

IF OBJECT_ID('LOREM_IPSUM.BI_H_PROMOCION','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_H_PROMOCION;

IF OBJECT_ID('LOREM_IPSUM.BI_D_RANGO_ETARIO','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_RANGO_ETARIO;

IF OBJECT_ID('LOREM_IPSUM.BI_D_TURNOS','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_TURNOS;

IF OBJECT_ID('LOREM_IPSUM.BI_D_UBICACION','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_UBICACION;

IF OBJECT_ID('LOREM_IPSUM.BI_D_TIEMPO','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_TIEMPO;

IF OBJECT_ID('LOREM_IPSUM.BI_D_SUCURSAL','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_SUCURSAL;

IF OBJECT_ID('LOREM_IPSUM.BI_D_MEDIO_PAGO','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_MEDIO_PAGO;

IF OBJECT_ID('LOREM_IPSUM.BI_D_CATEGORIA','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_CATEGORIA;

IF OBJECT_ID('LOREM_IPSUM.BI_D_SUBCATEGORIA','U') IS NOT NULL
    DROP TABLE LOREM_IPSUM.BI_D_SUBCATEGORIA;

-------------------- Creación de tablas ---------------------------

CREATE TABLE LOREM_IPSUM.BI_D_RANGO_ETARIO(
    RANGO_ETARIO_ID    SMALLINT IDENTITY(1,1) NOT NULL,
    RANGO_ETARIO_DESCRIPCION    NVARCHAR(50)
)



CREATE TABLE LOREM_IPSUM.BI_D_TURNOS(
    TURNO_ID            SMALLINT IDENTITY(1,1) NOT NULL,
    TURNO_DESCRIPCION   NVARCHAR(50)
)


CREATE TABLE LOREM_IPSUM.BI_D_UBICACION(
    UBI_ID              SMALLINT IDENTITY(1,1) NOT NULL,
    UBI_PROVINCIA       NVARCHAR(55),
    UBI_LOCALIDAD       NVARCHAR(55)
)



CREATE TABLE LOREM_IPSUM.BI_D_TIEMPO(
    TIEMPO_ID               SMALLINT IDENTITY(1,1) NOT NULL,
    TIEMPO_ANIO             SMALLINT,
    TIEMPO_CUATRIMESTRE     SMALLINT,
    TIEMPO_MES              SMALLINT
)


CREATE TABLE LOREM_IPSUM.BI_D_SUCURSAL(
    SUCURSAL_ID         SMALLINT IDENTITY(1,1) NOT NULL,
    SUCURSAL_DETALLE    NVARCHAR(255)
)


CREATE TABLE LOREM_IPSUM.BI_D_MEDIO_PAGO(
    MP_ID               INT IDENTITY(1,1) NOT NULL,
    MP_TIPO             INT               NOT NULL,
    MP_DETALLE          NVARCHAR(55)
)


CREATE TABLE LOREM_IPSUM.BI_D_CATEGORIA(
    CAT_ID          SMALLINT IDENTITY(1,1) NOT NULL,
    CAT_NOMBRE      NVARCHAR(50)
)



CREATE TABLE LOREM_IPSUM.BI_D_SUBCATEGORIA(
    SUBCAT_ID       SMALLINT IDENTITY(1,1) NOT NULL,
    SUBCAT_DESC     NVARCHAR(50)
)



CREATE TABLE LOREM_IPSUM.BI_H_VENTAS(
    VENT_ID                     INT IDENTITY(1,1) NOT NULL,
    VENT_RANGO_ETARIO_CLIENTE   SMALLINT NOT NULL,
    VENT_RANGO_ETARIO_EMPLEADO  SMALLINT NOT NULL,
    VENT_TIEMPO                 SMALLINT NOT NULL,
    VENT_SUCURSAL               SMALLINT NOT NULL,
    VENT_UBICACION              SMALLINT NOT NULL,
    VENT_TURNOS                 SMALLINT NOT NULL,
    VENT_CANTIDAD               INT,
    VENT_MONTO                  DECIMAL(18,2),
    VENT_DESCUENTO              DECIMAL(18,2)
)



CREATE TABLE LOREM_IPSUM.BI_H_PAGOS(
    PAGO_ID                     SMALLINT IDENTITY(1,1) NOT NULL,
    PAGO_UBICAION               SMALLINT NOT NULL,
    PAGO_TIEMPO                 SMALLINT NOT NULL,
    PAGO_RANGO_ETARIO_CLIENTE   SMALLINT NOT NULL,
    PAGO_MEDIO_PAGO             SMALLINT NOT NULL,
    PAGO_TURNO                  SMALLINT NOT NULL,
    PAGO_SUCURSAL               SMALLINT NOT NULL,
    PAGO_TOTAL                  DECIMAL(18,2) NOT NULL,
    PAGO_CUOTAS                 SMALLINT,
    PAGO_DESCUENTO              DECIMAL(18,2)
)

CREATE TABLE LOREM_IPSUM.BI_H_ENVIOS(
    ENV_ID                      INT IDENTITY(1,1) NOT NULL,
    ENV_UBICACION               SMALLINT NOT NULL,
    ENV_TIEMPO                  SMALLINT NOT NULL,
    ENV_RANGO_ETARIO_CLIENTE    SMALLINT NOT NULL,
    ENV_COSTO                   DECIMAL(18,2) NOT NULL,
    ENV_ATRASADO                BOOLEAN NOT NULL
)

CREATE TABLE LOREM_IPSUM.BI_H_PROMOCION(
    PROMO_ID            INT IDENTITY(1,1) NOT NULL,
    PROMO_TIEMPO        SMALLINT NOT NULL,
    PROMO_SUCURSAL      SMALLINT NOT NULL,
    PROMO_UBICACION     SMALLINT NOT NULL,
    PROMO_MONTO         DECIMAL(18,2) NOT NULL,
)

-------------------- Creación de primary keys ---------------------------

ALTER TABLE LOREM_IPSUM.BI_D_RANGO_ETARIO
ADD CONSTRAINT PK_BI_D_RANGO_ETARIO PRIMARY KEY (RANGO_ETARIO_ID);

ALTER TABLE LOREM_IPSUM.BI_D_TURNOS
ADD CONSTRAINT PK_BI_D_TURNOS PRIMARY KEY (TURNO_ID);

ALTER TABLE LOREM_IPSUM.BI_D_UBICACION
ADD CONSTRAINT PK_BI_D_UBICACION PRIMARY KEY (UBI_ID);

ALTER TABLE LOREM_IPSUM.BI_D_TIEMPO
ADD CONSTRAINT PK_BI_D_TIEMPO PRIMARY KEY (TIEMPO_ID);

ALTER TABLE LOREM_IPSUM.BI_D_SUCURSAL
ADD CONSTRAINT PK_BI_D_SUCURSAL PRIMARY KEY (SUCURSAL_ID);

ALTER TABLE LOREM_IPSUM.BI_D_MEDIO_PAGO
ADD CONSTRAINT PK_BI_D_MEDIO_PAGO PRIMARY KEY (MP_ID);

ALTER TABLE LOREM_IPSUM.BI_D_CATEGORIA
ADD CONSTRAINT PK_BI_D_CATEGORIA PRIMARY KEY (CAT_ID);

ALTER TABLE LOREM_IPSUM.BI_D_SUBCATEGORIA
ADD CONSTRAINT PK_BI_D_SUBCATEGORIA PRIMARY KEY (SUBCAT_ID);

-------------------- Creación de foreign keys ---------------------------

ALTER TABLE LOREM_IPSUM.BI_H_VENTAS
ADD CONSTRAINT FK_VENT_RANGO_ETARIO_CLIENTE
FOREIGN KEY (VENT_RANGO_ETARIO_CLIENTE) REFERENCES LOREM_IPSUM.BI_D_RANGO_ETARIO(RANGO_ETARIO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_VENTAS
ADD CONSTRAINT FK_VENT_RANGO_ETARIO_EMPLEADO
FOREIGN KEY (VENT_RANGO_ETARIO_EMPLEADO) REFERENCES LOREM_IPSUM.BI_D_RANGO_ETARIO(RANGO_ETARIO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_VENTAS
ADD CONSTRAINT FK_VENT_TIEMPO
FOREIGN KEY (VENT_TIEMPO) REFERENCES LOREM_IPSUM.BI_D_TIEMPO(TIEMPO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_VENTAS
ADD CONSTRAINT FK_VENT_SUCURSAL
FOREIGN KEY (VENT_SUCURSAL) REFERENCES LOREM_IPSUM.BI_D_SUCURSAL(SUCURSAL_ID);

ALTER TABLE LOREM_IPSUM.BI_H_VENTAS
ADD CONSTRAINT FK_VENT_UBICACION
FOREIGN KEY (VENT_UBICACION) REFERENCES LOREM_IPSUM.BI_D_UBICACION(UBI_ID);

ALTER TABLE LOREM_IPSUM.BI_H_VENTAS
ADD CONSTRAINT FK_VENT_TURNOS
FOREIGN KEY (VENT_TURNOS) REFERENCES LOREM_IPSUM.BI_D_TURNOS(TURNO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PAGOS
ADD CONSTRAINT FK_PAGO_UBICACION
FOREIGN KEY (PAGO_UBICAION) REFERENCES LOREM_IPSUM.BI_D_UBICACION(UBI_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PAGOS
ADD CONSTRAINT FK_PAGO_TIEMPO
FOREIGN KEY (PAGO_TIEMPO) REFERENCES LOREM_IPSUM.BI_D_TIEMPO(TIEMPO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PAGOS
ADD CONSTRAINT FK_PAGO_RANGO_ETARIO_CLIENTE
FOREIGN KEY (PAGO_RANGO_ETARIO_CLIENTE) REFERENCES LOREM_IPSUM.BI_D_RANGO_ETARIO(RANGO_ETARIO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PAGOS
ADD CONSTRAINT FK_PAGO_MEDIO_PAGO
FOREIGN KEY (PAGO_MEDIO_PAGO) REFERENCES LOREM_IPSUM.BI_D_MEDIO_PAGO(MP_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PAGOS
ADD CONSTRAINT FK_PAGO_TURNO
FOREIGN KEY (PAGO_TURNO) REFERENCES LOREM_IPSUM.BI_D_TURNOS(TURNO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PAGOS
ADD CONSTRAINT FK_PAGO_SUCURSAL
FOREIGN KEY (PAGO_SUCURSAL) REFERENCES LOREM_IPSUM.BI_D_SUCURSAL(SUCURSAL_ID);

ALTER TABLE LOREM_IPSUM.BI_H_ENVIOS
ADD CONSTRAINT FK_ENV_UBICACION
FOREIGN KEY (ENV_UBICACION) REFERENCES LOREM_IPSUM.BI_D_UBICACION(UBI_ID);

ALTER TABLE LOREM_IPSUM.BI_H_ENVIOS
ADD CONSTRAINT FK_ENV_TIEMPO
FOREIGN KEY (ENV_TIEMPO) REFERENCES LOREM_IPSUM.BI_D_TIEMPO(TIEMPO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_ENVIOS
ADD CONSTRAINT FK_ENV_RANGO_ETARIO_CLIENTE
FOREIGN KEY (ENV_RANGO_ETARIO_CLIENTE) REFERENCES LOREM_IPSUM.BI_D_RANGO_ETARIO(RANGO_ETARIO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PROMOCION
ADD CONSTRAINT FK_PROMO_TIEMPO
FOREIGN KEY (PROMO_TIEMPO) REFERENCES LOREM_IPSUM.BI_D_TIEMPO(TIEMPO_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PROMOCION
ADD CONSTRAINT FK_PROMO_SUCURSAL
FOREIGN KEY (PROMO_SUCURSAL) REFERENCES LOREM_IPSUM.BI_D_SUCURSAL(SUCURSAL_ID);

ALTER TABLE LOREM_IPSUM.BI_H_PROMOCION
ADD CONSTRAINT FK_PROMO_UBICACION
FOREIGN KEY (PROMO_UBICACION) REFERENCES LOREM_IPSUM.BI_D_UBICACION(UBI_ID);























